-- MySQL Script generated by MySQL Workbench
-- sex 21 jun 2019 19:00:57 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_bocavermelha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bocavermelha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bocavermelha` DEFAULT CHARACTER SET utf8 ;
USE `db_bocavermelha` ;

-- -----------------------------------------------------
-- Table `db_bocavermelha`.`FAIXA_ETARIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bocavermelha`.`FAIXA_ETARIA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fae_descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bocavermelha`.`CONEXAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bocavermelha`.`CONEXAO` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`con_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bocavermelha`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bocavermelha`.`CATEGORIA` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bocavermelha`.`STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bocavermelha`.`STATUS` (
  `sta_id` INT NOT NULL AUTO_INCREMENT,
  `sta_descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`sta_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bocavermelha`.`DENUNCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bocavermelha`.`DENUNCIA` (
  `den_id` INT NOT NULL AUTO_INCREMENT,
  `den_nome_vitima` VARCHAR(60) NOT NULL,
  `den_endereco_vitima` VARCHAR(255) NOT NULL,
  `fae_id_vitima` INT NOT NULL,
  `den_nome_suspeito` VARCHAR(60) NOT NULL,
  `den_endereco_suspeito` VARCHAR(255) NOT NULL,
  `fae_id_suspeito` INT NOT NULL,
  `den_outros_suspeitos` TEXT NULL,
  `con_id` INT NOT NULL,
  `den_local_ocorrencia` VARCHAR(255) NOT NULL,
  `den_desc_ocorrencia` TEXT NOT NULL,
  `den_uf_ocorrencia` VARCHAR(2) NOT NULL,
  `cat_id` INT NOT NULL,
  `sta_id` INT NOT NULL,
  `den_cd_acompanhamento` VARCHAR(16) NOT NULL,
  `den_dt_criacao` DATETIME NOT NULL,
  `den_dt_modificacao` DATETIME NOT NULL,
  `den_mensagem` TEXT NULL,
  PRIMARY KEY (`den_id`),
  INDEX `fk_fae_id_vitima_idx` (`fae_id_vitima` ASC),
  INDEX `fk_fae_id_suspeitp_idx` (`fae_id_suspeito` ASC),
  INDEX `fk_con_id_idx` (`con_id` ASC),
  INDEX `fk_cat_id_idx` (`cat_id` ASC),
  INDEX `fk_sta_id_idx` (`sta_id` ASC),
  CONSTRAINT `fk_fae_id_vitima`
    FOREIGN KEY (`fae_id_vitima`)
    REFERENCES `db_bocavermelha`.`FAIXA_ETARIA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fae_id_suspeitp`
    FOREIGN KEY (`fae_id_suspeito`)
    REFERENCES `db_bocavermelha`.`FAIXA_ETARIA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_con_id`
    FOREIGN KEY (`con_id`)
    REFERENCES `db_bocavermelha`.`CONEXAO` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cat_id`
    FOREIGN KEY (`cat_id`)
    REFERENCES `db_bocavermelha`.`CATEGORIA` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sta_id`
    FOREIGN KEY (`sta_id`)
    REFERENCES `db_bocavermelha`.`STATUS` (`sta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
